/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BiomorphsImport } from './routes/biomorphs'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const BiomorphsRoute = BiomorphsImport.update({
  id: '/biomorphs',
  path: '/biomorphs',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/biomorphs': {
      id: '/biomorphs'
      path: '/biomorphs'
      fullPath: '/biomorphs'
      preLoaderRoute: typeof BiomorphsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biomorphs': typeof BiomorphsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biomorphs': typeof BiomorphsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/biomorphs': typeof BiomorphsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/biomorphs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/biomorphs'
  id: '__root__' | '/' | '/biomorphs'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiomorphsRoute: typeof BiomorphsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiomorphsRoute: BiomorphsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/biomorphs"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/biomorphs": {
      "filePath": "biomorphs.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
